agent:
  agent_type: "ReActAgent"
  agent_kwargs:
    model: "gpt-4o"
    temperature: 1.0

rollout:
  max_steps: 25
  batch_size: 16
  rollout_type: "aviary"

notebook:
  name: "notebook.ipynb"
  language: "python"

capsule:
  mode: "open"
  include_refusal_option: true
  system_prompt: "CAPSULE_SYSTEM_PROMPT_OPEN"
  prompt_templates:
    mcq: "MCQ_PROMPT_TEMPLATE"
    open: "OPEN_PROMPT_TEMPLATE"
    hypothesis: "HYPOTHESIS_PROMPT_TEMPLATE"
  eval_mode: "LLM"
  avoid_images: true

paths:
  workspace_dir: "data/workspace"
  trajectories_dir: "data/trajectories"
  data_folder: "data/capsules"
  hf_repo_id: "futurehouse/bixbench-internal"

postprocessing:
  total_questions: 296
  total_iterations: 10